server:
  port: 8282
spring:
  security:
    user:
      name: karim
      password: karim123
      roles: ADMIN,USER
security:
  oauth2:
    client:
      client-id: postman
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client-credential
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll
